networks:

  external:
    name: 'dinosaur-external'
    internal: false

  internal:
    name: 'dinosaur-internal'
    internal: true

services:

  backend:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    networks:
      - external
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080/tcp

  frontend:
    restart: unless-stopped
    networks:
      - external
      - internal
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 3000:80/tcp
